#!/system/bin/sh

######### IMPORT BOOTKALI INITIALIZATION #########
SCRIPT_PATH=$(readlink -f $0)

#################################################
#### DEFINE ENVIRONMENT VARIABLES FOR CHROOT ####
#################################################

######### EXPORT ENVIRONMENT #########
export bin=/system/bin
PRESERVED_PATH=$PATH
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export USER=root
export LOGNAME=root
unset LD_PRELOAD

######### TERMINAL SETUP #########
clear
