#!/system/bin/sh

######### IMPORT BOOTKALI INITIALIZATION #########
SCRIPT_PATH=$(readlink -f $0)
. ${SCRIPT_PATH%/*}/bootkali_log

#################################################
#### DEFINE ENVIRONMENT VARIABLES FOR CHROOT ####
#################################################

export SHELL=/bin/bash
export bin=/system/bin
PRESERVED_PATH=$PATH
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=xterm-256color
export HOME=/root
export USER=root
export LOGNAME=root
export MAIL=/var/mail/root
export PWD=/root
export OLDPWD=/root

unset LD_PRELOAD

clear