#!/system/bin/sh

##########################################################################
#### DEFINE GLOBAL ENVIRONMENT VARIABLES FOR ALL NETHUNTER APP SCRIPT ####
##########################################################################

unset LD_PRELOAD

## Define the nethunter app package name.
APP_PGK_NAME=com.team420.kekhunter

## Define the root directory path of chroot containers
NHSYSTEM_PATH=/data/local/nhsystem

## Define chroot sudo path
CHROOT_EXEC=/usr/bin/sudo

## Combine android $PATH to kali chroot $PATH
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

## Define busybox path.
BUSYBOX=`which busybox_nh | head -n1`
if [ -z "$BUSYBOX" ]; then
    if [ -x "/system/xbin/busybox_nh" ]; then
        BUSYBOX="/system/xbin/busybox_nh"
    elif [ -x "/system/bin/busybox_nh" ]; then
        BUSYBOX="/system/bin/busybox_nh"
    elif [ -x "/data/data/$APP_PGK_NAME/files/scripts/bin/busybox_nh" ]; then
        BUSYBOX="/data/data/$APP_PGK_NAME/files/scripts/bin/busybox_nh"
    fi
fi

## Define the Kali Chroot path.
MNT=`readlink -e $NHSYSTEM_PATH/kalifs`
if [ -z "$MNT" ]; then
    MNT=`cat /data/data/$APP_PGK_NAME/shared_prefs/$APP_PGK_NAME.xml | grep "\"chroot_path\"" | sed "s/^.*\"chroot_path\">\(.*\)<\/string>/\1/g"`
fi

## Define the path of xz tool
XZ=/data/data/$APP_PGK_NAME/files/scripts/bin/xz
